version: '3.3'

services:
  project.redis: 
    image: redis:6.0 
    container_name: project.redis
      
  project.db: 
    image: mysql:8.0 
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci 
    container_name: project.db 
    restart: always 
    environment: 
      MYSQL_ROOT_PASSWORD: 123456 
      MYSQL_USER: "laravel-project" 
      MYSQL_PASSWORD: "goodday"
    volumes:
      - /home/mysql-master:/var/lib/mysql 
      - type: bind 
        source: ./compose/mysql/my.cnf 
        target: /etc/mysql/my.cnf
    ports:
      - 3308:3306 
      
  project.adminer:
    image: phpmyadmin 
    container_name: project.phpmyadmin 
    depends_on:
      - project.db 
    restart: always 
    ports: 
      - 16996:80
    environment: 
      PMA_HOST: project.db 
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: 123456
      #PMA_USER: "root" 
      #PMA_PASSWORD: "123456" 
      PMA_ARBITRARY: 1

  project.myapp:
    tty: true
    build: 
        context: .
        dockerfile: ./laravel/Dockerfile
    image: markhsieh4good/laravel:8.6.9-0.1 
    container_name: project.myapp 
    environment:
      - DB_HOST=project.db
      - DB_USERNAME=laravel-project
      - DB_DATABASE=laravel-project
      - DB_PASSWORD=goodday
    depends_on:
      - project.db
    ports:
      - 3000:3000
    volumes:
      - ./source:/app
    # privileged: true # Privileged mode could be required to run this container under Windows

networks: 
  default: 
    external: 
      name: project-bridge 
